# TCL File Generated by Component Editor 18.1
# Wed Jan 30 20:52:38 EET 2019
# DO NOT MODIFY


# 
# SHA256_calc "SHA256 calculator" v1.0
#  2019.01.30.20:52:38
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module SHA256_calc
# 
set_module_property DESCRIPTION ""
set_module_property NAME SHA256_calc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "SHA256 calculator"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Sha256AXI4
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Sha256AXI4.v VERILOG PATH Sha256AXI4.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock clock_sink
set_interface_property altera_axi4lite_slave associatedReset reset
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave io_ra_addr araddr Input 8
add_interface_port altera_axi4lite_slave io_ra_ready arready Output 1
add_interface_port altera_axi4lite_slave io_ra_valid arvalid Input 1
add_interface_port altera_axi4lite_slave io_wa_addr awaddr Input 8
add_interface_port altera_axi4lite_slave io_wa_ready awready Output 1
add_interface_port altera_axi4lite_slave io_wa_valid awvalid Input 1
add_interface_port altera_axi4lite_slave io_b_ready bready Input 1
add_interface_port altera_axi4lite_slave io_b_valid bvalid Output 1
add_interface_port altera_axi4lite_slave io_b_resp bresp Output 2
add_interface_port altera_axi4lite_slave io_rd_data rdata Output 32
add_interface_port altera_axi4lite_slave io_rd_ready rready Input 1
add_interface_port altera_axi4lite_slave io_rd_valid rvalid Output 1
add_interface_port altera_axi4lite_slave io_rd_resp rresp Output 2
add_interface_port altera_axi4lite_slave io_wd_data wdata Input 32
add_interface_port altera_axi4lite_slave io_wd_ready wready Output 1
add_interface_port altera_axi4lite_slave io_wd_strb wstrb Input 4
add_interface_port altera_axi4lite_slave io_wd_valid wvalid Input 1
add_interface_port altera_axi4lite_slave io_ra_prot arprot Input 3
add_interface_port altera_axi4lite_slave io_wa_prot awprot Input 3


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1

